blogTitle = "Scott Nonnenberg"
authorShortName = "Scott"
authorName = "Scott Nonnenberg"
authorEmail = "scott@nonnenberg.com"
authorTwitter = "@scottnonnenberg"
authorURL = "https://scottnonnenberg.com"
authorImage = "https://www.gravatar.com/avatar/6d4e229c0d24e92a2d15499acab531d8?d=404"
authorBlurb = "Hi, I'm <a href='https://scottnonnenberg.com'><strong>Scott</strong></a>. I'm a <a href='http://calpoly.edu'>Computer Science major</a> turned <a href='http://visualstudio.com'>Visual Studio</a> program manager, now consultant and entrepreneur. <a href='mailto:scott@nonnenberg.com'>Contact me</a> if you need some training, coding, or just an experienced outside perspective!"
linkPrefix = "/"
domain = "https://blog.scottnonnenberg.com"
tagLine = "A blog about software development and geekery of all kinds."
domainCDN = "https://static.sinap.ps"
domainPiwik = "https://piwik.sinap.ps"
