blogTitle = "Scott Nonnenberg"
authorName = "Scott Nonnenberg"
authorEmail = "scott@nonnenberg.com"
authorURL = "http://scottnonnenberg.com"
authorShortName = "Scott"
linkPrefix = "/"
domain = "https://blog-scottnonnenberg.gcap.ps"
tagLine = "A blog about software development and geekery of all kinds."
domainCDN = "https://static.gcap.ps"
domainPiwik = "https://piwik.gcap.ps"
